// Generated by CoffeeScript 1.7.1
var activeCounty, activeDimension, allCountyData, bb, blockContextMenu, canvasHeight, canvasWidth, color, colorDomains, constant, counties, countyAdded, dimensions, drawPC, drawVisualization, firstTime, graphContainer, graphFrame, graphLine, graphMask, graphXAxis, graphXScale, graphYAxis, graphYScale, graphedCountyId, labels, mapContainer, mapFrame, mapMask, mapX, mapY, modifyGraph, nationalData, parseDate, path, pcFrame, pcScales, projection, resetChoropleth, scaleY, standardMargin, svg, usGeo, windowHeight, windowWidth, zeroes, zoomChoropleth, _ref, _ref1;

windowWidth = 0.95 * window.innerWidth;

windowHeight = 0.8 * window.innerHeight;

standardMargin = windowHeight * (20 / 800);

canvasWidth = windowWidth - 2 * standardMargin;

canvasHeight = windowHeight - 2 * standardMargin;

svg = d3.select("#visualization").append("svg").attr("width", canvasWidth + 2 * standardMargin).attr("height", canvasHeight + 3 * standardMargin).append("g").attr("transform", "translate(" + standardMargin + ", " + standardMargin + ")");

constant = {
  rightMargin: canvasWidth * (500 / 1600),
  leftMargin: canvasWidth * (100 / 1600),
  verticalSeparator: canvasHeight * (20 / 800),
  horizontalSeparator: canvasWidth * (30 / 1600),
  graphClipHorizontalOffset: canvasWidth * (5 / 1600),
  graphClipVerticalOffset: canvasHeight * (50 / 800),
  zoomBox: standardMargin * 2,
  stateBorderWidth: 1,
  recolorDuration: 1000,
  choroplethDuration: 750,
  graphDuration: 500,
  nationalTitleOffset: -75,
  vsOffset: -8,
  countyTitleOffset: 5,
  labelY: canvasHeight * (7 / 800),
  tooltipOffset: canvasWidth * (5 / 1600),
  pcOffset: 0.2
};

dimensions = ['MedianListPrice', 'MedianListPricePerSqft', 'PctOfListingsWithPriceReductions', 'MedianPctOfPriceReduction', 'ZriPerSqft'];

labels = {
  'MedianListPrice': "Median list price ($)",
  'MedianListPricePerSqft': "Median list price / ft² ($)",
  'PctOfListingsWithPriceReductions': "Listings with price cut (%)",
  'MedianPctOfPriceReduction': "Median price reduction (%)",
  'ZriPerSqft': "Median rent price / ft² ($)"
};

colorDomains = {
  'MedianListPrice': [0, 70000, 90000, 100000, 150000, 200000, 250000, 500000, 5000000],
  'MedianListPricePerSqft': [0, 20, 40, 60, 100, 200, 300, 500, 1300],
  'PctOfListingsWithPriceReductions': [0, 5, 10, 20, 25, 30, 35, 40, 100],
  'MedianPctOfPriceReduction': [0, 2, 4, 6, 8, 10, 15, 20, 100],
  'ZriPerSqft': [0, 0.25, 0.5, 0.75, 1, 1.5, 2, 3, 5]
};

pcScales = {
  'MedianListPrice': [colorDomains['MedianListPrice'][8], colorDomains['MedianListPrice'][0]],
  'MedianListPricePerSqft': [colorDomains['MedianListPricePerSqft'][8], colorDomains['MedianListPricePerSqft'][0]],
  'PctOfListingsWithPriceReductions': [colorDomains['PctOfListingsWithPriceReductions'][8], colorDomains['PctOfListingsWithPriceReductions'][0]],
  'MedianPctOfPriceReduction': [colorDomains['MedianPctOfPriceReduction'][8], colorDomains['MedianPctOfPriceReduction'][0]],
  'ZriPerSqft': [colorDomains['ZriPerSqft'][8], colorDomains['ZriPerSqft'][0]]
};

activeDimension = dimensions[0];

_ref = [{}, null], nationalData = _ref[0], usGeo = _ref[1];

bb = {
  map: {
    x: 0,
    y: 0,
    width: canvasWidth - constant.rightMargin,
    height: canvasHeight * (2 / 3)
  },
  graph: {
    x: constant.leftMargin,
    y: canvasHeight * (2 / 3) + constant.verticalSeparator,
    width: canvasWidth - constant.rightMargin - constant.leftMargin,
    height: canvasHeight * (1 / 3) - constant.verticalSeparator
  },
  pc: {
    x: canvasWidth - constant.rightMargin + constant.horizontalSeparator,
    y: 0,
    width: constant.rightMargin - constant.horizontalSeparator,
    height: canvasHeight + constant.verticalSeparator
  }
};

mapContainer = svg.append("g").attr("transform", "translate(" + bb.map.x + ", " + bb.map.y + ")");

mapContainer.append("clipPath").attr("id", "mapClip").append("rect").attr("width", bb.map.width).attr("height", bb.map.height);

mapMask = mapContainer.append("g").attr("clip-path", "url(#mapClip)");

mapFrame = mapMask.append("g").attr("id", "mapFrame").attr("width", bb.map.width).attr("height", bb.map.height).style("stroke-width", "" + constant.stateBorderWidth + "px");

blockContextMenu = function(event) {
  return event.preventDefault();
};

document.querySelector('#mapFrame').addEventListener('contextmenu', blockContextMenu);

activeCounty = d3.select(null);

zoomChoropleth = function(d) {
  var bounds, dx, dy, scale, translate, x, y;
  if (activeCounty.node() === this) {
    return resetChoropleth();
  }
  activeCounty.classed("active", false);
  activeCounty = d3.select(this).classed("active", true);
  bounds = path.bounds(d);
  dx = bounds[1][0] - bounds[0][0] + constant.zoomBox;
  dy = bounds[1][1] - bounds[0][1] + constant.zoomBox;
  x = (bounds[0][0] + bounds[1][0]) / 2;
  y = (bounds[0][1] + bounds[1][1]) / 2;
  scale = 0.9 / Math.max(dx / bb.map.width, dy / bb.map.height);
  translate = [bb.map.width / 2 - scale * x, bb.map.height / 2 - scale * y];
  return mapFrame.transition().duration(constant.choroplethDuration).style("stroke-width", "" + (constant.stateBorderWidth / scale) + "px").attr("transform", "translate(" + translate + ")scale(" + scale + ")");
};

resetChoropleth = function() {
  activeCounty.classed("active", false);
  activeCounty = d3.select(null);
  return mapFrame.transition().duration(constant.choroplethDuration).style("stroke-width", "" + constant.stateBorderWidth + "px").attr("transform", "");
};

mapFrame.append("rect").attr("id", "mapBackground").attr("width", bb.map.width).attr("height", bb.map.height).on("click", resetChoropleth);

graphContainer = svg.append("g").attr("transform", "translate(" + (bb.graph.x - constant.leftMargin) + ", " + (bb.graph.y - constant.verticalSeparator) + ")");

graphContainer.append("clipPath").attr("id", "graphClip").append("rect").attr("width", bb.graph.width + constant.leftMargin + constant.graphClipHorizontalOffset).attr("height", bb.graph.height + constant.verticalSeparator + constant.graphClipVerticalOffset);

graphMask = graphContainer.append("g").attr("clip-path", "url(#graphClip)");

graphFrame = graphMask.append("g").attr("transform", "translate(" + constant.leftMargin + ", " + constant.verticalSeparator + ")").attr("id", "graphFrame").attr("width", bb.map.width).attr("height", bb.map.height);

parseDate = d3.time.format("%Y-%m").parse;

graphXScale = d3.time.scale().range([0, bb.graph.width]);

graphYScale = d3.scale.linear().range([bb.graph.height, constant.verticalSeparator / 2]);

graphXAxis = d3.svg.axis().scale(graphXScale).orient("bottom");

graphYAxis = d3.svg.axis().scale(graphYScale).ticks([5]).orient("left");

graphLine = d3.svg.line().interpolate("linear").x(function(d, i) {
  return graphXScale(nationalData.dates[i]);
}).y(function(d) {
  return graphYScale(+d);
});

scaleY = function(countyArray, nationalValues) {
  var allValues, point, _i, _len;
  allValues = [].concat(nationalValues.map(function(n) {
    return +n;
  }));
  for (_i = 0, _len = countyArray.length; _i < _len; _i++) {
    point = countyArray[_i];
    allValues.push(+point);
  }
  graphYScale.domain(d3.extent(allValues));
  return graphFrame.select(".y.axis").transition().duration(constant.graphDuration).call(graphYAxis);
};

countyAdded = false;

graphedCountyId = null;

zeroes = [];

modifyGraph = function(d, nationalValues) {
  var countyArray;
  if (d.id === graphedCountyId) {
    return;
  } else {
    graphedCountyId = d.id;
  }
  countyArray = d.properties[activeDimension];
  if (!countyAdded) {
    countyAdded = true;
    graphFrame.select(".title.national").transition().duration(constant.graphDuration).attr("transform", function(d) {
      return "translate(" + (bb.graph.width / 2 + constant.nationalTitleOffset) + ", 0)";
    });
    graphFrame.append("text").attr("class", "title vs").attr("text-anchor", "middle").attr("transform", "translate(" + (bb.graph.width * 1.5) + ", 0)").style("opacity", 0).text("vs.");
    graphFrame.select(".title.vs").transition().duration(constant.graphDuration).style("opacity", 1).attr("transform", "translate(" + (bb.graph.width / 2 + constant.vsOffset) + ", 0)");
    graphFrame.append("text").attr("class", "title county").attr("text-anchor", "start").attr("transform", "translate(" + (bb.graph.width * 1.5) + ", 0)").style("opacity", 0).text("" + d.properties.name);
    graphFrame.select(".title.county").transition().duration(constant.graphDuration).style("opacity", 1).attr("transform", "translate(" + (bb.graph.width / 2 + constant.countyTitleOffset) + ", 0)");
    scaleY(countyArray, nationalValues);
    graphFrame.select(".line.national").transition().duration(constant.graphDuration).attr("d", graphLine);
    graphFrame.selectAll(".point.national").transition().duration(constant.graphDuration).attr("transform", function(d, i) {
      return "translate(" + (graphXScale(nationalData.dates[i])) + ", " + (graphYScale(d)) + ")";
    });
    zeroes = [];
    countyArray.forEach(function() {
      return zeroes.push(0);
    });
    graphFrame.append("path").datum(zeroes).attr("class", "line county invisible").attr("d", graphLine);
    graphFrame.selectAll(".point.county.invisible").data(zeroes).enter().append("circle").attr("class", "point county invisible").attr("transform", function(d, i) {
      return "translate(" + (graphXScale(nationalData.dates[i])) + ", " + (graphYScale(d)) + ")";
    }).attr("r", 3);
    graphFrame.select(".line.county.invisible").datum(countyArray).attr("class", "line county").transition().duration(constant.graphDuration).attr("d", graphLine);
    return graphFrame.selectAll(".point.county.invisible").data(countyArray).attr("class", "point county").transition().duration(constant.graphDuration).attr("transform", function(d, i) {
      return "translate(" + (graphXScale(nationalData.dates[i])) + ", " + (graphYScale(d)) + ")";
    });
  } else {
    graphFrame.select(".title.county").transition().duration(constant.graphDuration / 2).attr("transform", "translate(" + (bb.graph.width / 2 + constant.countyTitleOffset) + ", " + constant.verticalSeparator + ")").style("opacity", 0).remove();
    graphFrame.append("text").attr("class", "title county").attr("text-anchor", "start").attr("transform", "translate(" + (bb.graph.width / 2 + constant.countyTitleOffset) + ", " + (-constant.verticalSeparator) + ")").style("opacity", 0).text("" + d.properties.name).transition().delay(constant.graphDuration / 2).duration(constant.graphDuration / 2).attr("transform", "translate(" + (bb.graph.width / 2 + constant.countyTitleOffset) + ", 0)").style("opacity", 1);
    scaleY(countyArray, nationalValues);
    graphFrame.select(".line.national").transition().duration(constant.graphDuration).attr("d", graphLine);
    graphFrame.selectAll(".point.national").transition().duration(constant.graphDuration).attr("transform", function(d, i) {
      return "translate(" + (graphXScale(nationalData.dates[i])) + ", " + (graphYScale(d)) + ")";
    });
    graphFrame.select(".line.county").datum(countyArray).transition().duration(constant.graphDuration).attr("d", graphLine);
    return graphFrame.selectAll(".point.county").data(countyArray).transition().duration(constant.graphDuration).attr("transform", function(d, i) {
      return "translate(" + (graphXScale(nationalData.dates[i])) + ", " + (graphYScale(d)) + ")";
    });
  }
};

pcFrame = svg.append("g").attr("id", "pcFrame").attr("transform", "translate(" + bb.pc.x + ", " + bb.pc.y + ")");

mapX = bb.map.width / 2;

mapY = bb.map.height / 2;

projection = d3.geo.albersUsa().scale(1.4 * windowHeight).translate([mapX, mapY]);

path = d3.geo.path().projection(projection);

color = d3.scale.threshold().domain([0, 25, 50, 75, 125, 150, 200, 500, 1500]).range(colorbrewer.YlGn[9]);

drawPC = function() {
  var add, allDataPresent, array, axis, background, brush, countyData, dimension, dragging, foreground, g, key, line, national, pcPath, position, properties, timeSlice, transition, x, y, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _len5, _m, _n;
  timeSlice = 5;
  allDataPresent = [];
  for (_i = 0, _len = allCountyData.length; _i < _len; _i++) {
    countyData = allCountyData[_i];
    properties = countyData.properties;
    add = true;
    for (_j = 0, _len1 = dimensions.length; _j < _len1; _j++) {
      dimension = dimensions[_j];
      if (properties[dimension].length === 0) {
        add = false;
        continue;
      }
      if (properties[dimension][timeSlice] === "") {
        add = false;
      }
    }
    if (add === true) {
      allDataPresent.push(countyData.properties);
    }
  }
  for (key in nationalData) {
    array = nationalData[key];
    if (key !== "dates") {
      allDataPresent.push(array);
    }
  }
  for (_k = 0, _len2 = allDataPresent.length; _k < _len2; _k++) {
    countyData = allDataPresent[_k];
    for (_l = 0, _len3 = dimensions.length; _l < _len3; _l++) {
      dimension = dimensions[_l];
      pcScales[dimension][0] = Math.min(pcScales[dimension][0], d3.min(countyData[dimension]));
      pcScales[dimension][1] = Math.max(pcScales[dimension][1], d3.max(countyData[dimension]));
    }
  }
  y = d3.scale.ordinal().rangePoints([0, bb.pc.height], constant.pcOffset);
  x = {};
  dragging = {};
  for (_m = 0, _len4 = dimensions.length; _m < _len4; _m++) {
    dimension = dimensions[_m];
    dragging[dimension] = null;
  }
  line = d3.svg.line();
  axis = d3.svg.axis().orient("bottom").ticks([5]);
  y.domain(dimensions);
  for (_n = 0, _len5 = dimensions.length; _n < _len5; _n++) {
    dimension = dimensions[_n];
    x[dimension] = d3.scale.linear().domain(pcScales[dimension]).range([0, bb.pc.width]);
  }
  position = function(d) {
    var v;
    v = dragging[d];
    if (v === null) {
      return y(d);
    }
    return v;
  };
  pcPath = function(d) {
    return line(dimensions.map(function(p) {
      return [x[p](+d[p][timeSlice]), position(p)];
    }));
  };
  transition = function(g) {
    return g.transition().duration(500);
  };
  brush = function() {
    var actives, extents;
    actives = dimensions.filter(function(p) {
      return !x[p].brush.empty();
    });
    extents = actives.map(function(p) {
      return x[p].brush.extent();
    });
    foreground.style("display", function(d) {
      var allmet;
      allmet = actives.every(function(p, i) {
        var value;
        value = d[p][timeSlice];
        return (extents[i][0] <= value) && (value <= extents[i][1]);
      });
      if (allmet === false) {
        return "none";
      }
    });
    return national.style("display", function(d) {
      var allmet;
      allmet = actives.every(function(p, i) {
        var value;
        value = d[p][timeSlice];
        return (extents[i][0] <= value) && (value <= extents[i][1]);
      });
      if (allmet === false) {
        return "none";
      }
    });
  };
  background = pcFrame.append("g").attr("class", "pcbackground").selectAll("path").data(allDataPresent).enter().append("path").attr("d", pcPath);
  foreground = pcFrame.append("g").attr("class", "pcforeground").selectAll("path").data(allDataPresent).enter().append("path").attr("d", pcPath);
  national = pcFrame.append("g").datum(nationalData).attr("class", "pcnational").append("path").attr("d", pcPath);
  g = pcFrame.selectAll(".dimension").data(dimensions).enter().append("g").attr("class", "dimension").attr("transform", function(d) {
    return "translate(0, " + (y(d)) + ")";
  });
  g.append("g").attr("class", "pcaxis").each(function(d) {
    return d3.select(this).call(axis.scale(x[d]));
  }).append("text").attr("text-anchor", "end").attr("x", bb.pc.width).attr("y", -9).text(function(d) {
    return labels[d];
  });
  return g.append("g").attr("class", "pcbrush").each(function(d) {
    return d3.select(this).call(x[d].brush = d3.svg.brush().x(x[d]).on("brush", brush));
  }).selectAll("rect").attr("y", -8).attr("height", 16);
};

_ref1 = [null, null], allCountyData = _ref1[0], counties = _ref1[1];

drawVisualization = function(firstTime) {
  var nationalPoints, nationalValues, timeSlice;
  nationalValues = nationalData[activeDimension];
  color.domain(colorDomains[activeDimension]);
  timeSlice = nationalValues.length - 1;
  if (firstTime) {
    allCountyData = topojson.feature(usGeo, usGeo.objects.counties).features;
    counties = mapFrame.append("g").attr("id", "counties").selectAll(".county").data(allCountyData).enter().append("path").attr("class", "county").attr("d", path).style("fill", function(d) {
      var countyData;
      countyData = d.properties[activeDimension];
      if (countyData.length === 0) {
        return "#d9d9d9";
      } else {
        if (countyData[timeSlice] === "") {
          return "#d9d9d9";
        } else {
          return color(countyData[timeSlice]);
        }
      }
    }).style("opacity", 1.0).on("click", zoomChoropleth);
    mapFrame.append("path").attr("id", "state-borders").datum(topojson.mesh(usGeo, usGeo.objects.states, function(a, b) {
      return a !== b;
    })).attr("d", path);
  } else {
    counties.transition().duration(constant.recolorDuration).style("fill", function(d) {
      var countyData;
      countyData = d.properties[activeDimension];
      if (countyData.length === 0) {
        return "#d9d9d9";
      } else {
        if (countyData[timeSlice] === "") {
          return "#d9d9d9";
        } else {
          return color(countyData[timeSlice]);
        }
      }
    });
  }
  counties.on("contextmenu", function(d) {
    if (d.properties[activeDimension].length === 0) {

    } else if (d.properties[activeDimension][timeSlice] === "") {

    } else {
      return modifyGraph(d, nationalValues);
    }
  });
  counties.on("mouseover", function(d) {
    if (d.properties[activeDimension].length === 0) {

    } else if (d.properties[activeDimension][timeSlice] === "") {

    } else {
      d3.select(this).style("opacity", 0.8);
    }
    d3.select("#tooltip").style("left", "" + (d3.event.pageX + constant.tooltipOffset) + "px").style("top", "" + (d3.event.pageY + constant.tooltipOffset) + "px");
    d3.select("#county").text(d.properties.name);
    return d3.select("#tooltip").classed("hidden", false);
  });
  counties.on("mouseout", function(d) {
    d3.select("#tooltip").classed("hidden", true);
    return d3.select(this).transition().duration(250).style("opacity", 1.0);
  });
  graphYScale.domain(d3.extent(nationalValues));
  if (firstTime) {
    graphXScale.domain([nationalData.dates[0], nationalData.dates[nationalData.dates.length - 1]]);
    graphFrame.append("g").attr("class", "x axis").attr("transform", "translate(0, " + bb.graph.height + ")").call(graphXAxis);
    graphFrame.append("g").attr("class", "y axis").call(graphYAxis);
    graphFrame.append("text").attr("class", "title national").attr("text-anchor", "middle").attr("transform", "translate(" + (bb.graph.width / 2) + ", 0)").text("National Trend");
    graphFrame.append("text").attr("class", "y label").attr("text-anchor", "end").attr("y", constant.labelY).attr("dy", ".75em").attr("transform", "rotate(-90)").text(labels[activeDimension]);
    graphFrame.append("path").datum(nationalData[activeDimension]).attr("class", "line national").attr("d", graphLine);
    return graphFrame.selectAll(".point.national").data(nationalData[activeDimension]).enter().append("circle").attr("class", "point national").attr("transform", function(d, i) {
      return "translate(" + (graphXScale(nationalData.dates[i])) + ", " + (graphYScale(+d)) + ")";
    }).attr("r", 3);
  } else {
    graphFrame.select(".y.axis").transition().duration(constant.graphDuration).call(graphYAxis);
    graphFrame.select(".title.vs").transition().duration(constant.graphDuration).attr("transform", "translate(" + (bb.graph.width / 2 + constant.vsOffset) + ", " + constant.verticalSeparator + ")").style("opacity", 0).remove();
    graphFrame.select(".title.county").transition().duration(constant.graphDuration).attr("transform", "translate(" + (bb.graph.width / 2 + constant.countyTitleOffset) + ", " + constant.verticalSeparator + ")").style("opacity", 0).remove();
    graphFrame.select(".title.national").transition().duration(constant.graphDuration).attr("transform", "translate(" + (bb.graph.width / 2) + ", 0)");
    graphFrame.select(".y.label").transition().duration(constant.graphDuration / 2).style("opacity", 0);
    graphFrame.select(".y.label").transition().delay(constant.graphDuration / 2).duration(constant.graphDuration / 2).text(labels[activeDimension]).style("opacity", 1);
    graphFrame.select(".line.county").remove();
    graphFrame.selectAll(".point.county").remove();
    graphFrame.select(".line.national").datum(nationalData[activeDimension]).transition().duration(constant.graphDuration).attr("d", graphLine);
    nationalPoints = graphFrame.selectAll(".point.national").data(nationalData[activeDimension]);
    nationalPoints.transition().duration(constant.graphDuration).attr("transform", function(d, i) {
      return "translate(" + (graphXScale(nationalData.dates[i])) + ", " + (graphYScale(d)) + ")";
    });
    nationalPoints.enter().append("circle").attr("class", "point national").transition().duration(constant.graphDuration).attr("transform", function(d, i) {
      return "translate(" + (graphXScale(nationalData.dates[i])) + ", " + (graphYScale(d)) + ")";
    }).attr("r", 3);
    return nationalPoints.exit().remove();
  }
};

firstTime = true;

d3.selectAll("input[name='dimensionSwitch']").on("click", function() {
  if (+this.value === dimensions.indexOf(activeDimension)) {

  } else {
    activeDimension = dimensions[this.value];
    countyAdded = false;
    graphedCountyId = null;
    return drawVisualization(firstTime);
  }
});

d3.json("../data/compressed-nationwide-data.json", function(nationwide) {
  return d3.json("../data/compressed-augmented-us-states-and-counties.json", function(us) {
    var _ref2;
    _ref2 = [nationwide, us], nationalData = _ref2[0], usGeo = _ref2[1];
    nationalData.dates = nationalData.dates.map(function(dateString) {
      return parseDate(dateString);
    });
    drawVisualization(firstTime);
    return firstTime = !firstTime;
  });
});
